# Generated by Django 5.2 on 2025-04-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurent',
            old_name='restaurent_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='restaurent',
            old_name='picture_url',
            new_name='picture',
        ),
    ]
