# Generated by Django 5.2 on 2025-05-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_restaurant_picture_menu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Items',
        ),
    ]
